### ISSUE TITLE
同款电脑，同efi，亮度调节已经解决，但是触摸板无法使用

### ISSUE THREAD

**Issue by hcd6688** [axap288/redmibook-hackintosh-efi#3]
同款电脑，同efi，亮度调节已经解决，但是触摸板无法使用
<img width="1424" alt="截屏2020-04-19下午2 59 56" src="https://user-images.githubusercontent.com/63108861/79681703-b42b0680-824e-11ea-96fe-1f0589375340.png">

**Comment by hcd6688** [comment]
<img width="780" alt="截屏2020-04-19下午3 04 42" src="https://user-images.githubusercontent.com/63108861/79681755-23a0f600-824f-11ea-95b1-ede11cd4cb71.png">

**Comment by axap288** [comment]
![Screen Shot 2020-04-21 at 10 58 13](https://user-images.githubusercontent.com/872544/79820522-025f1780-83bf-11ea-8cd2-6eb2a67256ce.png)
我这可以呀，难道是玄学问题 😂

**Comment by axap288** [comment]
> 同款电脑，同efi，亮度调节已经解决，但是触摸板无法使用
> <img alt="截屏2020-04-19下午2 59 56" width="1424" src="https://user-images.githubusercontent.com/63108861/79681703-b42b0680-824e-11ea-96fe-1f0589375340.png">

亮度调节怎么做到的？

**Comment by hcd6688** [comment]
你好，感谢你提供efi文件，你的efi中有很多多余的驱动，可以删除（亲测有效）。我个人认为你亮度不能调节是因为HDMI影响的，你的efi在hackintool中显示屏不是内建的，所以系统中无法调节亮度。但是我使用一段时间感觉不太稳定，前两天突然进不了系统，所以我重新配置了efi文件，触摸板可以使用了，亮度是打的补丁实现的，HDMI是改Mac mini才可以输出，声卡ID改为21后很稳定

<img width="882" alt="截屏2020-04-21上午11 25 11" src="https://user-images.githubusercontent.com/63108861/79822675-51f41200-83c4-11ea-9526-f53b0286ac96.png">
<img width="863" alt="截屏2020-04-21上午11 29 59" src="https://user-images.githubusercontent.com/63108861/79822676-53253f00-83c4-11ea-898e-ec7071727f2c.png">
<img width="780" alt="截屏2020-04-21上午11 20 27" src="https://user-images.githubusercontent.com/63108861/79822677-54ef0280-83c4-11ea-9629-f9791feac989.png">
![WechatIMG1](https://user-images.githubusercontent.com/63108861/79822881-c8910f80-83c4-11ea-89f4-d321b3d3ac65.jpeg)
![Uploading WechatIMG2.jpeg…]()

**Comment by hcd6688** [comment]
【补充一下】因为我更换了白果卡，所以用不到博通的驱动。你efi中博通网卡驱动别删

**Comment by hcd6688** [comment]
![Uploading WechatIMG1.jpeg…]()
![Uploading WechatIMG2.jpeg…]()

**Comment by hcd6688** [comment]
你可以试试我的亮度补丁
<img width="882" alt="截屏2020-04-21上午11 45 24" src="https://user-images.githubusercontent.com/63108861/79823425-5d483d00-83c6-11ea-8dd4-1dfb6943def8.png">
[DSDT.aml.zip](https://github.com/axap288/redmibook-hackintosh-efi/files/4507550/DSDT.aml.zip)

**Comment by axap288** [comment]
> 你好，感谢你提供efi文件，你的efi中有很多多余的驱动，可以删除（亲测有效）。我个人认为你亮度不能调节是因为HDMI影响的，你的efi在hackintool中显示屏不是内建的，所以系统中无法调节亮度。但是我使用一段时间感觉不太稳定，前两天突然进不了系统，所以我重新配置了efi文件，触摸板可以使用了，亮度是打的补丁实现的，HDMI是改Mac mini才可以输出，声卡ID改为21后很稳定
> 
> <img alt="截屏2020-04-21上午11 25 11" width="882" src="https://user-images.githubusercontent.com/63108861/79822675-51f41200-83c4-11ea-9526-f53b0286ac96.png">
> 
> <img alt="截屏2020-04-21上午11 29 59" width="863" src="https://user-images.githubusercontent.com/63108861/79822676-53253f00-83c4-11ea-898e-ec7071727f2c.png">
> 
> <img alt="截屏2020-04-21上午11 20 27" width="780" src="https://user-images.githubusercontent.com/63108861/79822677-54ef0280-83c4-11ea-9629-f9791feac989.png">
> 
> ![WechatIMG1](https://user-images.githubusercontent.com/63108861/79822881-c8910f80-83c4-11ea-89f4-d321b3d3ac65.jpeg) ![Uploading WechatIMG2.jpeg…]()

感谢你的分享🤝 有些驱动确实是多余的，我也试试你的亮度补丁哈，可以的话我更新一下哈，谢谢

**Comment by hcd6688** [comment]
如果有用请回来告诉我一声

**Comment by axap288** [comment]
![Screen Shot 2020-04-21 at 12 07 43](https://user-images.githubusercontent.com/872544/79824369-b7e29880-83c8-11ea-9a51-bc47129ce9c6.png)

![Screen Shot 2020-04-21 at 12 06 16](https://user-images.githubusercontent.com/872544/79824292-84a00980-83c8-11ea-83d3-e1a6be001f3b.png)

亮度可以调节了，但是看上去对显示器的识别不太一样。这块你是怎么设置的？

**Comment by hcd6688** [comment]
你好，请问是显示器无法显示还是颜色不正常

**Comment by hcd6688** [comment]
亮度调节可以使用电脑原生按键。你需要先插入一个USB键盘，并打开设置-键盘-快捷键-显示器-改为f3 f4之后拔掉USB键盘。之后就可以使用电脑原生按键fn＋f3/f4调节亮度

**Comment by axap288** [comment]
功能都正常，就是这个界面显示跟你不一样
![](https://user-images.githubusercontent.com/63108861/79681755-23a0f600-824f-11ea-95b1-ede11cd4cb71.png)

**Comment by hcd6688** [comment]
因为我们电脑屏幕是1080p的，不是苹果4k的屏幕，而在这个情况下，电脑屏幕字很小。
我是开启了苹果自带的显示器hidpi高清缩放，让电脑显示器更细腻

**Comment by hcd6688** [comment]
[Uploading hidpi.sh.zip…]()

**Comment by axap288** [comment]
> Uploading hidpi.sh.zip…

OK~了解了，多谢，麻烦这个文件再发一次，好像没上传上来

**Comment by hcd6688** [comment]
先打开终端
1.输入sudo -s     回车
2.输入密码，    回车
3.输入chmod a+x  拖我发给你的文件     回车
关闭终端

**Comment by hcd6688** [comment]
我这里上传了，要不然qq 2661961048 加我，不收费白嫖的

**Comment by axap288** [comment]
哈哈，就喜欢白嫖的，加你了
